# Example
# https://gitpod.io/#TDK_PHP_VERSION=8.1,TDK_BRANCH=main,TDK_PATCH_REF=refs%2Fchanges%2F43%2F70643%2F36,TDK_USERNAME=ochorocho,TDK_PATCH_ID=70643/https://github.com/ochorocho/tdk/tree/task/gitpod-optimize
image: gitpod/workspace-mysql

tasks:
  - name: TYPO3 TDK
    init: |
      mkdir -p .vscode
      cp -Rp .gitpod/vscode/settings.json .vscode/settings.json
      sudo update-alternatives --set php $(which php${TDK_PHP_VERSION:=8.1})
      mysql -e "CREATE DATABASE db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;"
      mysql -e "CREATE USER 'db'@'localhost' IDENTIFIED BY 'db';"
      mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'db'@'localhost';"
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';" -uroot -ppassword
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';" -uroot -ppassword
      mysql -e "FLUSH PRIVILEGES;" -uroot -ppassword
      gp open .gitpod/info.md
      composer tdk:clone
      composer tdk:checkout
      composer install
      composer tdk:set-git-config
      composer tdk:enable-hooks -- --force
      composer tdk:apply-patch
      touch public/FIRST_INSTALL
      mkdir public/typo3conf
      cp -Rp .gitpod/typo3/AdditionalConfiguration.php public/typo3conf/AdditionalConfiguration.php
    command: |
      nix-env -iA nixpkgs.mailhog
      nohup MailHog >/dev/null 2>&1 &
      echo "export TYPO3_CONTEXT=Development" >> /etc/apache2/envvars
      echo -e "max_execution_time=240\nmax_input_vars=1500" | sudo tee -a /etc/php/${TDK_PHP_VERSION:=8.1}/cli/conf.d/40-php.ini | sudo tee -a  /etc/php/${TDK_PHP_VERSION:=8.1}/apache2/conf.d/40-php.ini
      echo "gp preview \$(gp url 8001) --external" | sudo tee -a /usr/local/bin/t3-fe
      echo "gp preview \$(gp url 8001)/typo3 --external" | sudo tee -a /usr/local/bin/t3-be
      echo "gp preview \$(gp url 8025) --external" | sudo tee -a /usr/local/bin/t3-mailhog
      echo "touch \$GITPOD_REPO_ROOTS/public/typo3conf/ENABLE_INSTALL_TOOL && gp preview \$(gp url 8001)/typo3/install.php --external" | sudo tee -a /usr/local/bin/t3-install
      sudo chmod +x /usr/local/bin/t3-*
      composer tdk:help
      apachectl start
      t3-fe

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql

ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 8025
    onOpen: ignore
