image: gitpod/workspace-mysql
tasks:
  - init: |
      sudo update-alternatives --set php $(which php${TDK_PHP_VERSION:=8.1})
      sudo echo -e "max_execution_time=240\nmax_input_vars=1500" | sudo tee -a  /etc/php/${TDK_PHP_VERSION:=8.1}/cli/conf.d/40-php.ini | sudo tee -a  /etc/php/${TDK_PHP_VERSION:=8.1}/apache2/conf.d/40-php.ini
    command: |
      composer tdk:clone
      composer tdk:checkout
      composer install
      composer tdk:set-git-config
      composer tdk:enable-hooks -- --force
      composer tdk:apply-patch
      ddev start
      touch public/FIRST_INSTALL
      composer tdk:help
      apachectl start

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: ignore
