image:
  file: .gitpod/.gitpod.Dockerfile
tasks:
  - init: |
      echo "Init stuff"
    command: |
      .gitpod/utils/env-setup.sh
      composer tdk:clone
      composer tdk:checkout
      composer install
      composer tdk:set-git-config
      composer tdk:enable-hooks -- --force
      composer tdk:apply-patch
      ddev start
      touch public/FIRST_INSTALL
      composer tdk:help
  - name: preview setup
    openMode: split-right
    command: >
      gp open public/index.php && 
      gp sync-await npmdone && 
      gp await-port 3306 &&
      apachectl start &&
      ./node_modules/.bin/webpack --watch
# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

ports:
  - port: 3306
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 3005
    onOpen: open-preview